name = "cf-worker-telegram"
main = "./index.js"
compatibility_date = "2025-04-01"

[observability.logs]
enabled = true
invocation_logs = true

[vars]
SERVER_PROXY_URL = "https://vibe-proxy-ad34f0.vibefrens.net"
